DROP DATABASE IF EXISTS ivncr;
DROP ROLE IF EXISTS ivncr;

CREATE USER ivncr PASSWORD 'ivncr' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE ivncr
  WITH OWNER = ivncr
  ENCODING = 'UTF8'
  TABLESPACE = pg_default
  CONNECTION LIMIT = -1;
